### ISSUE TITLE
Create Login Page

### ISSUE THREAD

**Issue by hanmosh** [hack4impact-calpoly/ecologistics-shared-calendar#5]
**Description**
Create a bare bones login page

<img width="656" alt="Screenshot 2024-01-25 at 9 30 03 PM" src="https://github.com/hack4impact-calpoly/ecologistics-shared-calendar/assets/113932134/64fc4583-b6be-49db-9d57-9b72fca9a654">

**Acceptance Criteria**
Simple login page complete with routing from navbar 

**Steps:**
- Run "git pull" and "npm i" on dev branch
- Create a new branch for this issue and check it out 
    - !! Make sure to commit to your branch as you go. You should NOT be working on the dev branch !!
- Go to src -> pages and create a new js file titled "login.js"
- Create the front end for the page complete with text boxes and buttons, do not worry about connecting anything to backend yet (feel free to use other pages as a guide)
     - *Please use inline styling for now*
- Add the icons within the text box border (see if you can find here: https://mui.com/material-ui/material-icons/)  
- go to src -> components -> layout.js and add a link to the login page on the navbar

Other notes: 
- Once you assign yourself to this issue change the status under "projects"
- Once you are done and make a PR assign Hannah AND Muzart as your reviewers
- for details on font, color, etc. please refer to the Figma design (https://www.figma.com/file/4NJboGxoFPvhsco82SeuZl/Ecologistics-Calendar?type=design&node-id=71-571&mode=design&t=XEvfVXPUyLyyXfAf-0)

**Comment by Sahillather002** [comment]
pls assign
