### ISSUE TITLE
Pending Approval Page

### ISSUE THREAD

**Issue by hanmosh** [hack4impact-calpoly/ecologistics-shared-calendar#83]
**Description**
This is the page that shows up once you create an account and are waiting for it to be approved. There are two ways to reach this page: 
1. After the "Create an account flow", once you click sign up 
2. Anytime you try to log in with the email and password you created in create an account

<img width="676" alt="Screenshot 2024-04-24 at 3 06 34 PM" src="https://github.com/hack4impact-calpoly/ecologistics-shared-calendar/assets/113932134/6edb7ef2-8082-4620-baf4-48044aba4ab7">

Note: "Go to Calendar" button goes to the public calendar page in #82 , if this is not implemented yet just have it go to the regular calendar for now

Steps:
- Adjust the current pending approval page (confirmation-page.tsx) to match the Figma 
- make it reachable in the two above scenarios 

Request review from tech leads once finished

**Comment by mtbosio** [comment]
Changed verification page to look prettier and also have a better code input system. Tested it and still works

<img width="1788" alt="Screenshot 2024-04-30 at 5 20 32 PM" src="https://github.com/hack4impact-calpoly/ecologistics-shared-calendar/assets/102556901/673e1360-94a5-4c1a-b1e1-5106b392c74c">
