### ISSUE TITLE
Create Add Event Page

### ISSUE THREAD

**Issue by hanmosh** [hack4impact-calpoly/ecologistics-shared-calendar#9]
**Description**
Simple events page 

<img width="451" alt="Screenshot 2024-01-26 at 3 48 15 PM" src="https://github.com/hack4impact-calpoly/ecologistics-shared-calendar/assets/113932134/21d2ee6f-27eb-47cc-a7e8-50c2df47ade0">

**Acceptance Criteria**
Page matches Figma design  

Steps:
- Run "git pull" and "npm i" on dev branch
- Create a new branch for this issue and check it out
     - !! Make sure to commit to your branch as you go. You should NOT be working on the dev branch !!
- Go to src -> pages and create a new js file titled "addEvent.js"
- Create the front end for the page complete with text boxes and buttons, do not worry about connecting anything to backend yet  (feel free to use other pages as a guide)
       - research how to have a dropbox for images and implement that feature (would likely need a backend, so if you need access to a database please check with tech leads)
       - *Also: please use inline styling for now*
- go to src -> components -> layout.js and add a link to the page on the navbar

**Additional Information**
- Once you assign yourself to this issue change the status under "projects"
- Once you are done and make a PR assign Hannah AND Muzart as your reviewers
- For details on font, color, etc. please refer to the Figma design (https://www.figma.com/file/4NJboGxoFPvhsco82SeuZl/Ecologistics-Calendar?type=design&node-id=71-571&mode=design&t=ZwhPW9aF8lHJ1OA3-0)

**Comment by devinhadley** [comment]
```
const mongoose = require('mongoose');
const Schema = mongoose.Schema;

const eventSchema = new Schema({
  title: { type: String, required: true },
  startDate: { type: Date, required: true }, // Date object includes time.
  endDate: { type: Date, required: true }, // "
  description: { type: String, required: false },
  isVirtual: { type: Boolean, required: true },
  link: { type: String, required: function() { return this.isVirtual; } },
  imageLink: { type: String, required: false }
}, {
  timestamps: true 
});

const Event = mongoose.model('Event', eventSchema);

module.exports = Event;

```
